% FET_ANALYZER_EXAMPLES  Runnable MOSFET examples using paths relative to this folder.
%
% Open this script from MOSFET_analyze and run sections as needed.

mosfetDir = fileparts(mfilename('fullpath'));
dataDir = fullfile(mosfetDir, 'B1500_data_export');

transferFile = fullfile(dataDir, '# Transfer Curve [CHIP012_O7(3) ; 10_7_2025 9_56_45 PM].csv');
outputSeriesFile = fullfile(dataDir, '# Output Curve [CHIP012_O7(3) ; 10_7_2025 9_53_40 PM].csv');
outputSingleFile = fullfile(dataDir, 'Quick Check [(4) ; 7_10_2025 10_53_53 pm].csv');

% Auto-detect transfer data and analyze it.
outTransfer = import_clarius_csv(transferFile);
resTransfer = analyze_transfer_curves(outTransfer, ...
    "YLim", [1e-13, 1e-3], ...
    "DoPlot", true, ...
    "SmoothingPts", 5, ...
    "PeakFrac", 0.8, ...
    "IoffFrac", 3, ...
    "PadVg", 0.1, ...
    "MinWinPts", 12, ...
    "ComplianceFrac", 0.98, ...
    "DenoiseWindow", 5, ...
    "IrefFixed", 1e-7, ...
    "MinVonPoints", 6, ...
    "MinVonR2", 0.97, ...
    "MinVonSlope", 1e-12, ...
    "MinVonDeltaVg", 0.02);
resTransfer.Summary

% Force output-curve series analysis.
outOutputSeries = import_clarius_csv(outputSeriesFile, ...
    FileType="output_series", Plot=true);
resOutputSeries = analyze_output_curves(outOutputSeries, ...
    "VdLinMax", 0.1, ...
    "VdSatFrac", 0.6, ...
    "DoPlot", true, ...
    "WLCOX", [10e-6, 1e-6, 1e-2], ...
    "UseQuadFit", true);
resOutputSeries.Summary

% Single output curve example.
outOutputSingle = import_clarius_csv(outputSingleFile, ...
    FileType="output_single", Plot=true);
